language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to run before testing
before_script:
  - echo "no tests required"

script:
  - docker --version # print the docker version for loggin purposes
  - docker build -t simple-node-2 --build-arg FAVORITE_FOOD=${FAVORITE_FOOD} .
  - docker tag simple-node-2 esthercatheryn/simple-node-2:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push esthercatheryn/simple-node-2